print_string "Objective Categorical Abstract Machine Language\n";; (*imprime Exemple e pula uma linha*)
print_int 5;; (*imprime 5 *)
print_string "\n";; (*pula uma linha*)
print_int (5 * 5);; (*imprime o resultado de 5 x 5, ou seja, 25*)
print_string "\n";; (*pula uma linha*)